// Types are now generated by Prisma
// Import from @prisma/client instead
import type { Profile, Opportunity, Application, SavedOpportunity } from '@prisma/client';

// Re-export for convenience
export type { Profile, Opportunity, Application, SavedOpportunity };

// Enums
export { UserRole, OpportunityStatus, ApplicationStatus } from '@prisma/client';

// Extended types with relations
export interface OpportunityWithOrganization extends Opportunity {
  organization: Profile;
}

export interface ApplicationWithDetails extends Application {
  opportunity: OpportunityWithOrganization;
  volunteer: Profile;
}

export interface OpportunityFilters {
  category?: string;
  location?: string;
  remote?: boolean;
  skills?: string[];
  search?: string;
}

export const OPPORTUNITY_CATEGORIES = [
  'Education',
  'Environment',
  'Healthcare',
  'Community Development',
  'Animal Welfare',
  'Arts & Culture',
  'Technology',
  'Disaster Relief',
  'Senior Care',
  'Youth Programs',
] as const;

export const SKILL_OPTIONS = [
  'Teaching',
  'Mentoring',
  'Event Planning',
  'Fundraising',
  'Marketing',
  'Social Media',
  'Writing',
  'Design',
  'Photography',
  'Video Production',
  'Web Development',
  'Data Analysis',
  'Project Management',
  'Public Speaking',
  'Translation',
  'Cooking',
  'First Aid',
  'Manual Labor',
  'Administrative',
  'Counseling',
] as const;

