"""enhance_models_for_full_platform

Revision ID: 5247166cf38b
Revises: 52e8db08a552
Create Date: 2025-11-14 14:38:39.769071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5247166cf38b'
down_revision: Union[str, None] = '52e8db08a552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new enum types first
    op.execute("CREATE TYPE completionstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED')")
    op.execute("CREATE TYPE opportunitystatus AS ENUM ('DRAFT', 'ACTIVE', 'CLOSED', 'COMPLETED')")
    
    op.add_column('applications', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('completion_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='completionstatus'), nullable=True))
    op.add_column('applications', sa.Column('completion_requested_at', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('hours_completed', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('completion_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('completion_approved_at', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('completion_reviewed_by', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('completion_review_notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'applications', 'users', ['completion_reviewed_by'], ['id'])
    op.drop_column('applications', 'notes')
    op.add_column('opportunities', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('opportunities', sa.Column('application_deadline', sa.DateTime(), nullable=True))
    op.add_column('opportunities', sa.Column('spots_filled', sa.Integer(), nullable=True))
    op.add_column('opportunities', sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'COMPLETED', name='opportunitystatus'), nullable=True))
    op.create_index(op.f('ix_opportunities_category'), 'opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_opportunities_city'), 'opportunities', ['city'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.drop_column('opportunities', 'is_active')
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('availability', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('profile_visibility', sa.Boolean(), nullable=True))
    op.add_column('volunteer_history', sa.Column('application_id', sa.Integer(), nullable=True))
    op.alter_column('volunteer_history', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'volunteer_history', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer_history', type_='foreignkey')
    op.alter_column('volunteer_history', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('volunteer_history', 'application_id')
    op.drop_column('users', 'profile_visibility')
    op.drop_column('users', 'availability')
    op.drop_column('users', 'city')
    op.drop_column('organizations', 'category')
    op.drop_column('organizations', 'contact_phone')
    op.drop_column('organizations', 'contact_email')
    op.drop_column('organizations', 'city')
    op.add_column('opportunities', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_city'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_category'), table_name='opportunities')
    op.drop_column('opportunities', 'status')
    op.drop_column('opportunities', 'spots_filled')
    op.drop_column('opportunities', 'application_deadline')
    op.drop_column('opportunities', 'city')
    op.add_column('applications', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'completion_review_notes')
    op.drop_column('applications', 'completion_reviewed_by')
    op.drop_column('applications', 'completion_approved_at')
    op.drop_column('applications', 'completion_notes')
    op.drop_column('applications', 'hours_completed')
    op.drop_column('applications', 'completion_requested_at')
    op.drop_column('applications', 'completion_status')
    op.drop_column('applications', 'review_notes')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS opportunitystatus")
    op.execute("DROP TYPE IF EXISTS completionstatus")
    # ### end Alembic commands ###

